/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GisRouteImport } from './routes/gis'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JejuAgriIndexRouteImport } from './routes/jeju-agri/index'
import { Route as SpcLayoutRouteImport } from './routes/spc/_layout'
import { Route as BscLayoutRouteImport } from './routes/bsc/_layout'
import { Route as JejuAgriDetailIdIndexRouteImport } from './routes/jeju-agri/detail/$id/index'
import { Route as SpcLayoutRtlWhlslMrktShareRouteImport } from './routes/spc/_layout/rtl/whlsl-mrkt-share'
import { Route as SpcLayoutRtlPrcPredcRouteImport } from './routes/spc/_layout/rtl/prc-predc'
import { Route as SpcLayoutRtlPrcDsbrdRouteImport } from './routes/spc/_layout/rtl/prc-dsbrd'
import { Route as SpcLayoutRtlGarakPrcRouteImport } from './routes/spc/_layout/rtl/garak-prc'
import { Route as SpcLayoutRtlExpRouteImport } from './routes/spc/_layout/rtl/exp'
import { Route as SpcLayoutRtlCropTradeRouteImport } from './routes/spc/_layout/rtl/crop-trade'
import { Route as SpcLayoutProdRgnCltvtnHarvRouteImport } from './routes/spc/_layout/prod/rgn-cltvtn-harv'
import { Route as SpcLayoutProdRgnCifruCltvtnRouteImport } from './routes/spc/_layout/prod/rgn-cifru-cltvtn'
import { Route as SpcLayoutProdCropCltvtnMapRouteImport } from './routes/spc/_layout/prod/crop-cltvtn-map'
import { Route as SpcLayoutProdCltvarChagRouteImport } from './routes/spc/_layout/prod/cltvar-chag'
import { Route as SpcLayoutProdAgingRouteImport } from './routes/spc/_layout/prod/aging'
import { Route as SpcLayoutObsrvnQltyRouteImport } from './routes/spc/_layout/obsrvn/qlty'
import { Route as SpcLayoutObsrvnObsrvnInfoCmpRouteImport } from './routes/spc/_layout/obsrvn/obsrvn-info-cmp'
import { Route as SpcLayoutObsrvnFlntRouteImport } from './routes/spc/_layout/obsrvn/flnt'
import { Route as SpcLayoutObsrvnCifruTrageDistRouteImport } from './routes/spc/_layout/obsrvn/cifru-trage-dist'
import { Route as SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRouteImport } from './routes/spc/_layout/agrclt-env/yrly-agrclt-dstdmg'
import { Route as SpcLayoutAgrcltEnvWethrRouteImport } from './routes/spc/_layout/agrclt-env/wethr'
import { Route as SpcLayoutAgrcltEnvItemDamCsRouteImport } from './routes/spc/_layout/agrclt-env/item-dam-cs'
import { Route as SpcLayoutAgrcltEnvGwtWtrqltyChagRouteImport } from './routes/spc/_layout/agrclt-env/gwt-wtrqlty-chag'
import { Route as SpcLayoutAgrcltEnvGwtAnlsDsbrdRouteImport } from './routes/spc/_layout/agrclt-env/gwt-anls-dsbrd'
import { Route as SpcLayoutAgrcltEnvDstdmgTypeStatsRouteImport } from './routes/spc/_layout/agrclt-env/dstdmg-type-stats'
import { Route as SpcLayoutAgrcltEnvAgrcltDstdmgRouteImport } from './routes/spc/_layout/agrclt-env/agrclt-dstdmg'
import { Route as BscLayoutPrdctnMtrlFrmcnHldRouteImport } from './routes/bsc/_layout/prdctn-mtrl/frmcn-hld'
import { Route as BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRouteImport } from './routes/bsc/_layout/prdctn-mtrl/agrchm-frtlzr-ntsl'
import { Route as BscLayoutFrmlndUtztnRouteImport } from './routes/bsc/_layout/frmlnd/utztn'
import { Route as BscLayoutFrmlndAreaRouteImport } from './routes/bsc/_layout/frmlnd/area'
import { Route as BscLayoutFrmhsPpltnRouteImport } from './routes/bsc/_layout/frmhs/ppltn'
import { Route as BscLayoutFrmhsFrmlndSclRouteImport } from './routes/bsc/_layout/frmhs/frmlnd-scl'
import { Route as BscLayoutFrmhsAgeRtrrlRouteImport } from './routes/bsc/_layout/frmhs/age-rtrrl'
import { Route as BscLayoutFrmhsAgeRtfrmRouteImport } from './routes/bsc/_layout/frmhs/age-rtfrm'
import { Route as BscLayoutFrmhsAgePpltnRouteImport } from './routes/bsc/_layout/frmhs/age-ppltn'
import { Route as BscLayoutEcnmPrdtvIdctRouteImport } from './routes/bsc/_layout/ecnm/prdtv-idct'
import { Route as BscLayoutEcnmMngmtCostRouteImport } from './routes/bsc/_layout/ecnm/mngmt-cost'
import { Route as BscLayoutEcnmLbrinpRouteImport } from './routes/bsc/_layout/ecnm/lbrinp'
import { Route as BscLayoutEcnmLbltRouteImport } from './routes/bsc/_layout/ecnm/lblt'
import { Route as BscLayoutEcnmKeyIdctRouteImport } from './routes/bsc/_layout/ecnm/key-idct'
import { Route as BscLayoutEcnmGrsincmRouteImport } from './routes/bsc/_layout/ecnm/grsincm'
import { Route as BscLayoutEcnmEarnRouteImport } from './routes/bsc/_layout/ecnm/earn'
import { Route as BscLayoutEcnmCrastRouteImport } from './routes/bsc/_layout/ecnm/crast'
import { Route as BscLayoutEcnmAstRouteImport } from './routes/bsc/_layout/ecnm/ast'
import { Route as BscLayoutCltvarYieldWhtbrlRghgrnRouteImport } from './routes/bsc/_layout/cltvar-yield/whtbrl-rghgrn'
import { Route as BscLayoutCltvarYieldWhtbrlMldgrnRouteImport } from './routes/bsc/_layout/cltvar-yield/whtbrl-mldgrn'
import { Route as BscLayoutCltvarYieldRtvgtRouteImport } from './routes/bsc/_layout/cltvar-yield/rtvgt'
import { Route as BscLayoutCltvarYieldRtcrpRouteImport } from './routes/bsc/_layout/cltvar-yield/rtcrp'
import { Route as BscLayoutCltvarYieldPlsRouteImport } from './routes/bsc/_layout/cltvar-yield/pls'
import { Route as BscLayoutCltvarYieldMldgrnRouteImport } from './routes/bsc/_layout/cltvar-yield/mldgrn'
import { Route as BscLayoutCltvarYieldMiscgrnRouteImport } from './routes/bsc/_layout/cltvar-yield/miscgrn'
import { Route as BscLayoutCltvarYieldLfyvgtRouteImport } from './routes/bsc/_layout/cltvar-yield/lfyvgt'
import { Route as BscLayoutCltvarYieldIndcrpRouteImport } from './routes/bsc/_layout/cltvar-yield/indcrp'
import { Route as BscLayoutCltvarYieldFrtvgtRouteImport } from './routes/bsc/_layout/cltvar-yield/frtvgt'
import { Route as BscLayoutCltvarYieldCnvgtRouteImport } from './routes/bsc/_layout/cltvar-yield/cnvgt'
import { Route as BscLayoutCltvarYieldAdlfrtImtfrtRouteImport } from './routes/bsc/_layout/cltvar-yield/adlfrt-imtfrt'
import { Route as BscLayoutCltvarYieldAdlfrtRouteImport } from './routes/bsc/_layout/cltvar-yield/adlfrt'
import { Route as BscLayoutCifruRtlPrdstsVrtyRouteImport } from './routes/bsc/_layout/cifru-rtl/prdsts-vrty'
import { Route as BscLayoutCifruRtlOpfCifruRouteImport } from './routes/bsc/_layout/cifru-rtl/opf-cifru'
import { Route as BscLayoutCifruRtlHouseCifruRouteImport } from './routes/bsc/_layout/cifru-rtl/house-cifru'
import { Route as BscLayoutCifruRtlHinatCifruRouteImport } from './routes/bsc/_layout/cifru-rtl/hinat-cifru'
import { Route as BscLayoutCifruRtlCifruhybRouteImport } from './routes/bsc/_layout/cifru-rtl/cifruhyb'
import { Route as BscLayoutCifruRtlBscStatsRouteImport } from './routes/bsc/_layout/cifru-rtl/bsc-stats'

const SpcRouteImport = createFileRoute('/spc')()
const BscRouteImport = createFileRoute('/bsc')()

const SpcRoute = SpcRouteImport.update({
  id: '/spc',
  path: '/spc',
  getParentRoute: () => rootRouteImport,
} as any)
const BscRoute = BscRouteImport.update({
  id: '/bsc',
  path: '/bsc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JejuAgriIndexRoute = JejuAgriIndexRouteImport.update({
  id: '/jeju-agri/',
  path: '/jeju-agri/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpcLayoutRoute = SpcLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => SpcRoute,
} as any)
const BscLayoutRoute = BscLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => BscRoute,
} as any)
const JejuAgriDetailIdIndexRoute = JejuAgriDetailIdIndexRouteImport.update({
  id: '/jeju-agri/detail/$id/',
  path: '/jeju-agri/detail/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpcLayoutRtlWhlslMrktShareRoute =
  SpcLayoutRtlWhlslMrktShareRouteImport.update({
    id: '/rtl/whlsl-mrkt-share',
    path: '/rtl/whlsl-mrkt-share',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutRtlPrcPredcRoute = SpcLayoutRtlPrcPredcRouteImport.update({
  id: '/rtl/prc-predc',
  path: '/rtl/prc-predc',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutRtlPrcDsbrdRoute = SpcLayoutRtlPrcDsbrdRouteImport.update({
  id: '/rtl/prc-dsbrd',
  path: '/rtl/prc-dsbrd',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutRtlGarakPrcRoute = SpcLayoutRtlGarakPrcRouteImport.update({
  id: '/rtl/garak-prc',
  path: '/rtl/garak-prc',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutRtlExpRoute = SpcLayoutRtlExpRouteImport.update({
  id: '/rtl/exp',
  path: '/rtl/exp',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutRtlCropTradeRoute = SpcLayoutRtlCropTradeRouteImport.update({
  id: '/rtl/crop-trade',
  path: '/rtl/crop-trade',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutProdRgnCltvtnHarvRoute =
  SpcLayoutProdRgnCltvtnHarvRouteImport.update({
    id: '/prod/rgn-cltvtn-harv',
    path: '/prod/rgn-cltvtn-harv',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutProdRgnCifruCltvtnRoute =
  SpcLayoutProdRgnCifruCltvtnRouteImport.update({
    id: '/prod/rgn-cifru-cltvtn',
    path: '/prod/rgn-cifru-cltvtn',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutProdCropCltvtnMapRoute =
  SpcLayoutProdCropCltvtnMapRouteImport.update({
    id: '/prod/crop-cltvtn-map',
    path: '/prod/crop-cltvtn-map',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutProdCltvarChagRoute = SpcLayoutProdCltvarChagRouteImport.update({
  id: '/prod/cltvar-chag',
  path: '/prod/cltvar-chag',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutProdAgingRoute = SpcLayoutProdAgingRouteImport.update({
  id: '/prod/aging',
  path: '/prod/aging',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutObsrvnQltyRoute = SpcLayoutObsrvnQltyRouteImport.update({
  id: '/obsrvn/qlty',
  path: '/obsrvn/qlty',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutObsrvnObsrvnInfoCmpRoute =
  SpcLayoutObsrvnObsrvnInfoCmpRouteImport.update({
    id: '/obsrvn/obsrvn-info-cmp',
    path: '/obsrvn/obsrvn-info-cmp',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutObsrvnFlntRoute = SpcLayoutObsrvnFlntRouteImport.update({
  id: '/obsrvn/flnt',
  path: '/obsrvn/flnt',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutObsrvnCifruTrageDistRoute =
  SpcLayoutObsrvnCifruTrageDistRouteImport.update({
    id: '/obsrvn/cifru-trage-dist',
    path: '/obsrvn/cifru-trage-dist',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute =
  SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRouteImport.update({
    id: '/agrclt-env/yrly-agrclt-dstdmg',
    path: '/agrclt-env/yrly-agrclt-dstdmg',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutAgrcltEnvWethrRoute = SpcLayoutAgrcltEnvWethrRouteImport.update({
  id: '/agrclt-env/wethr',
  path: '/agrclt-env/wethr',
  getParentRoute: () => SpcLayoutRoute,
} as any)
const SpcLayoutAgrcltEnvItemDamCsRoute =
  SpcLayoutAgrcltEnvItemDamCsRouteImport.update({
    id: '/agrclt-env/item-dam-cs',
    path: '/agrclt-env/item-dam-cs',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutAgrcltEnvGwtWtrqltyChagRoute =
  SpcLayoutAgrcltEnvGwtWtrqltyChagRouteImport.update({
    id: '/agrclt-env/gwt-wtrqlty-chag',
    path: '/agrclt-env/gwt-wtrqlty-chag',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute =
  SpcLayoutAgrcltEnvGwtAnlsDsbrdRouteImport.update({
    id: '/agrclt-env/gwt-anls-dsbrd',
    path: '/agrclt-env/gwt-anls-dsbrd',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutAgrcltEnvDstdmgTypeStatsRoute =
  SpcLayoutAgrcltEnvDstdmgTypeStatsRouteImport.update({
    id: '/agrclt-env/dstdmg-type-stats',
    path: '/agrclt-env/dstdmg-type-stats',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const SpcLayoutAgrcltEnvAgrcltDstdmgRoute =
  SpcLayoutAgrcltEnvAgrcltDstdmgRouteImport.update({
    id: '/agrclt-env/agrclt-dstdmg',
    path: '/agrclt-env/agrclt-dstdmg',
    getParentRoute: () => SpcLayoutRoute,
  } as any)
const BscLayoutPrdctnMtrlFrmcnHldRoute =
  BscLayoutPrdctnMtrlFrmcnHldRouteImport.update({
    id: '/prdctn-mtrl/frmcn-hld',
    path: '/prdctn-mtrl/frmcn-hld',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute =
  BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRouteImport.update({
    id: '/prdctn-mtrl/agrchm-frtlzr-ntsl',
    path: '/prdctn-mtrl/agrchm-frtlzr-ntsl',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutFrmlndUtztnRoute = BscLayoutFrmlndUtztnRouteImport.update({
  id: '/frmlnd/utztn',
  path: '/frmlnd/utztn',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutFrmlndAreaRoute = BscLayoutFrmlndAreaRouteImport.update({
  id: '/frmlnd/area',
  path: '/frmlnd/area',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutFrmhsPpltnRoute = BscLayoutFrmhsPpltnRouteImport.update({
  id: '/frmhs/ppltn',
  path: '/frmhs/ppltn',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutFrmhsFrmlndSclRoute = BscLayoutFrmhsFrmlndSclRouteImport.update({
  id: '/frmhs/frmlnd-scl',
  path: '/frmhs/frmlnd-scl',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutFrmhsAgeRtrrlRoute = BscLayoutFrmhsAgeRtrrlRouteImport.update({
  id: '/frmhs/age-rtrrl',
  path: '/frmhs/age-rtrrl',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutFrmhsAgeRtfrmRoute = BscLayoutFrmhsAgeRtfrmRouteImport.update({
  id: '/frmhs/age-rtfrm',
  path: '/frmhs/age-rtfrm',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutFrmhsAgePpltnRoute = BscLayoutFrmhsAgePpltnRouteImport.update({
  id: '/frmhs/age-ppltn',
  path: '/frmhs/age-ppltn',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmPrdtvIdctRoute = BscLayoutEcnmPrdtvIdctRouteImport.update({
  id: '/ecnm/prdtv-idct',
  path: '/ecnm/prdtv-idct',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmMngmtCostRoute = BscLayoutEcnmMngmtCostRouteImport.update({
  id: '/ecnm/mngmt-cost',
  path: '/ecnm/mngmt-cost',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmLbrinpRoute = BscLayoutEcnmLbrinpRouteImport.update({
  id: '/ecnm/lbrinp',
  path: '/ecnm/lbrinp',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmLbltRoute = BscLayoutEcnmLbltRouteImport.update({
  id: '/ecnm/lblt',
  path: '/ecnm/lblt',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmKeyIdctRoute = BscLayoutEcnmKeyIdctRouteImport.update({
  id: '/ecnm/key-idct',
  path: '/ecnm/key-idct',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmGrsincmRoute = BscLayoutEcnmGrsincmRouteImport.update({
  id: '/ecnm/grsincm',
  path: '/ecnm/grsincm',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmEarnRoute = BscLayoutEcnmEarnRouteImport.update({
  id: '/ecnm/earn',
  path: '/ecnm/earn',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmCrastRoute = BscLayoutEcnmCrastRouteImport.update({
  id: '/ecnm/crast',
  path: '/ecnm/crast',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutEcnmAstRoute = BscLayoutEcnmAstRouteImport.update({
  id: '/ecnm/ast',
  path: '/ecnm/ast',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutCltvarYieldWhtbrlRghgrnRoute =
  BscLayoutCltvarYieldWhtbrlRghgrnRouteImport.update({
    id: '/cltvar-yield/whtbrl-rghgrn',
    path: '/cltvar-yield/whtbrl-rghgrn',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldWhtbrlMldgrnRoute =
  BscLayoutCltvarYieldWhtbrlMldgrnRouteImport.update({
    id: '/cltvar-yield/whtbrl-mldgrn',
    path: '/cltvar-yield/whtbrl-mldgrn',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldRtvgtRoute =
  BscLayoutCltvarYieldRtvgtRouteImport.update({
    id: '/cltvar-yield/rtvgt',
    path: '/cltvar-yield/rtvgt',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldRtcrpRoute =
  BscLayoutCltvarYieldRtcrpRouteImport.update({
    id: '/cltvar-yield/rtcrp',
    path: '/cltvar-yield/rtcrp',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldPlsRoute = BscLayoutCltvarYieldPlsRouteImport.update({
  id: '/cltvar-yield/pls',
  path: '/cltvar-yield/pls',
  getParentRoute: () => BscLayoutRoute,
} as any)
const BscLayoutCltvarYieldMldgrnRoute =
  BscLayoutCltvarYieldMldgrnRouteImport.update({
    id: '/cltvar-yield/mldgrn',
    path: '/cltvar-yield/mldgrn',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldMiscgrnRoute =
  BscLayoutCltvarYieldMiscgrnRouteImport.update({
    id: '/cltvar-yield/miscgrn',
    path: '/cltvar-yield/miscgrn',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldLfyvgtRoute =
  BscLayoutCltvarYieldLfyvgtRouteImport.update({
    id: '/cltvar-yield/lfyvgt',
    path: '/cltvar-yield/lfyvgt',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldIndcrpRoute =
  BscLayoutCltvarYieldIndcrpRouteImport.update({
    id: '/cltvar-yield/indcrp',
    path: '/cltvar-yield/indcrp',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldFrtvgtRoute =
  BscLayoutCltvarYieldFrtvgtRouteImport.update({
    id: '/cltvar-yield/frtvgt',
    path: '/cltvar-yield/frtvgt',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldCnvgtRoute =
  BscLayoutCltvarYieldCnvgtRouteImport.update({
    id: '/cltvar-yield/cnvgt',
    path: '/cltvar-yield/cnvgt',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldAdlfrtImtfrtRoute =
  BscLayoutCltvarYieldAdlfrtImtfrtRouteImport.update({
    id: '/cltvar-yield/adlfrt-imtfrt',
    path: '/cltvar-yield/adlfrt-imtfrt',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCltvarYieldAdlfrtRoute =
  BscLayoutCltvarYieldAdlfrtRouteImport.update({
    id: '/cltvar-yield/adlfrt',
    path: '/cltvar-yield/adlfrt',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCifruRtlPrdstsVrtyRoute =
  BscLayoutCifruRtlPrdstsVrtyRouteImport.update({
    id: '/cifru-rtl/prdsts-vrty',
    path: '/cifru-rtl/prdsts-vrty',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCifruRtlOpfCifruRoute =
  BscLayoutCifruRtlOpfCifruRouteImport.update({
    id: '/cifru-rtl/opf-cifru',
    path: '/cifru-rtl/opf-cifru',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCifruRtlHouseCifruRoute =
  BscLayoutCifruRtlHouseCifruRouteImport.update({
    id: '/cifru-rtl/house-cifru',
    path: '/cifru-rtl/house-cifru',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCifruRtlHinatCifruRoute =
  BscLayoutCifruRtlHinatCifruRouteImport.update({
    id: '/cifru-rtl/hinat-cifru',
    path: '/cifru-rtl/hinat-cifru',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCifruRtlCifruhybRoute =
  BscLayoutCifruRtlCifruhybRouteImport.update({
    id: '/cifru-rtl/cifruhyb',
    path: '/cifru-rtl/cifruhyb',
    getParentRoute: () => BscLayoutRoute,
  } as any)
const BscLayoutCifruRtlBscStatsRoute =
  BscLayoutCifruRtlBscStatsRouteImport.update({
    id: '/cifru-rtl/bsc-stats',
    path: '/cifru-rtl/bsc-stats',
    getParentRoute: () => BscLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/gis': typeof GisRoute
  '/login': typeof LoginRoute
  '/bsc': typeof BscLayoutRouteWithChildren
  '/spc': typeof SpcLayoutRouteWithChildren
  '/jeju-agri': typeof JejuAgriIndexRoute
  '/bsc/cifru-rtl/bsc-stats': typeof BscLayoutCifruRtlBscStatsRoute
  '/bsc/cifru-rtl/cifruhyb': typeof BscLayoutCifruRtlCifruhybRoute
  '/bsc/cifru-rtl/hinat-cifru': typeof BscLayoutCifruRtlHinatCifruRoute
  '/bsc/cifru-rtl/house-cifru': typeof BscLayoutCifruRtlHouseCifruRoute
  '/bsc/cifru-rtl/opf-cifru': typeof BscLayoutCifruRtlOpfCifruRoute
  '/bsc/cifru-rtl/prdsts-vrty': typeof BscLayoutCifruRtlPrdstsVrtyRoute
  '/bsc/cltvar-yield/adlfrt': typeof BscLayoutCltvarYieldAdlfrtRoute
  '/bsc/cltvar-yield/adlfrt-imtfrt': typeof BscLayoutCltvarYieldAdlfrtImtfrtRoute
  '/bsc/cltvar-yield/cnvgt': typeof BscLayoutCltvarYieldCnvgtRoute
  '/bsc/cltvar-yield/frtvgt': typeof BscLayoutCltvarYieldFrtvgtRoute
  '/bsc/cltvar-yield/indcrp': typeof BscLayoutCltvarYieldIndcrpRoute
  '/bsc/cltvar-yield/lfyvgt': typeof BscLayoutCltvarYieldLfyvgtRoute
  '/bsc/cltvar-yield/miscgrn': typeof BscLayoutCltvarYieldMiscgrnRoute
  '/bsc/cltvar-yield/mldgrn': typeof BscLayoutCltvarYieldMldgrnRoute
  '/bsc/cltvar-yield/pls': typeof BscLayoutCltvarYieldPlsRoute
  '/bsc/cltvar-yield/rtcrp': typeof BscLayoutCltvarYieldRtcrpRoute
  '/bsc/cltvar-yield/rtvgt': typeof BscLayoutCltvarYieldRtvgtRoute
  '/bsc/cltvar-yield/whtbrl-mldgrn': typeof BscLayoutCltvarYieldWhtbrlMldgrnRoute
  '/bsc/cltvar-yield/whtbrl-rghgrn': typeof BscLayoutCltvarYieldWhtbrlRghgrnRoute
  '/bsc/ecnm/ast': typeof BscLayoutEcnmAstRoute
  '/bsc/ecnm/crast': typeof BscLayoutEcnmCrastRoute
  '/bsc/ecnm/earn': typeof BscLayoutEcnmEarnRoute
  '/bsc/ecnm/grsincm': typeof BscLayoutEcnmGrsincmRoute
  '/bsc/ecnm/key-idct': typeof BscLayoutEcnmKeyIdctRoute
  '/bsc/ecnm/lblt': typeof BscLayoutEcnmLbltRoute
  '/bsc/ecnm/lbrinp': typeof BscLayoutEcnmLbrinpRoute
  '/bsc/ecnm/mngmt-cost': typeof BscLayoutEcnmMngmtCostRoute
  '/bsc/ecnm/prdtv-idct': typeof BscLayoutEcnmPrdtvIdctRoute
  '/bsc/frmhs/age-ppltn': typeof BscLayoutFrmhsAgePpltnRoute
  '/bsc/frmhs/age-rtfrm': typeof BscLayoutFrmhsAgeRtfrmRoute
  '/bsc/frmhs/age-rtrrl': typeof BscLayoutFrmhsAgeRtrrlRoute
  '/bsc/frmhs/frmlnd-scl': typeof BscLayoutFrmhsFrmlndSclRoute
  '/bsc/frmhs/ppltn': typeof BscLayoutFrmhsPpltnRoute
  '/bsc/frmlnd/area': typeof BscLayoutFrmlndAreaRoute
  '/bsc/frmlnd/utztn': typeof BscLayoutFrmlndUtztnRoute
  '/bsc/prdctn-mtrl/agrchm-frtlzr-ntsl': typeof BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute
  '/bsc/prdctn-mtrl/frmcn-hld': typeof BscLayoutPrdctnMtrlFrmcnHldRoute
  '/spc/agrclt-env/agrclt-dstdmg': typeof SpcLayoutAgrcltEnvAgrcltDstdmgRoute
  '/spc/agrclt-env/dstdmg-type-stats': typeof SpcLayoutAgrcltEnvDstdmgTypeStatsRoute
  '/spc/agrclt-env/gwt-anls-dsbrd': typeof SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute
  '/spc/agrclt-env/gwt-wtrqlty-chag': typeof SpcLayoutAgrcltEnvGwtWtrqltyChagRoute
  '/spc/agrclt-env/item-dam-cs': typeof SpcLayoutAgrcltEnvItemDamCsRoute
  '/spc/agrclt-env/wethr': typeof SpcLayoutAgrcltEnvWethrRoute
  '/spc/agrclt-env/yrly-agrclt-dstdmg': typeof SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute
  '/spc/obsrvn/cifru-trage-dist': typeof SpcLayoutObsrvnCifruTrageDistRoute
  '/spc/obsrvn/flnt': typeof SpcLayoutObsrvnFlntRoute
  '/spc/obsrvn/obsrvn-info-cmp': typeof SpcLayoutObsrvnObsrvnInfoCmpRoute
  '/spc/obsrvn/qlty': typeof SpcLayoutObsrvnQltyRoute
  '/spc/prod/aging': typeof SpcLayoutProdAgingRoute
  '/spc/prod/cltvar-chag': typeof SpcLayoutProdCltvarChagRoute
  '/spc/prod/crop-cltvtn-map': typeof SpcLayoutProdCropCltvtnMapRoute
  '/spc/prod/rgn-cifru-cltvtn': typeof SpcLayoutProdRgnCifruCltvtnRoute
  '/spc/prod/rgn-cltvtn-harv': typeof SpcLayoutProdRgnCltvtnHarvRoute
  '/spc/rtl/crop-trade': typeof SpcLayoutRtlCropTradeRoute
  '/spc/rtl/exp': typeof SpcLayoutRtlExpRoute
  '/spc/rtl/garak-prc': typeof SpcLayoutRtlGarakPrcRoute
  '/spc/rtl/prc-dsbrd': typeof SpcLayoutRtlPrcDsbrdRoute
  '/spc/rtl/prc-predc': typeof SpcLayoutRtlPrcPredcRoute
  '/spc/rtl/whlsl-mrkt-share': typeof SpcLayoutRtlWhlslMrktShareRoute
  '/jeju-agri/detail/$id': typeof JejuAgriDetailIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/gis': typeof GisRoute
  '/login': typeof LoginRoute
  '/bsc': typeof BscLayoutRouteWithChildren
  '/spc': typeof SpcLayoutRouteWithChildren
  '/jeju-agri': typeof JejuAgriIndexRoute
  '/bsc/cifru-rtl/bsc-stats': typeof BscLayoutCifruRtlBscStatsRoute
  '/bsc/cifru-rtl/cifruhyb': typeof BscLayoutCifruRtlCifruhybRoute
  '/bsc/cifru-rtl/hinat-cifru': typeof BscLayoutCifruRtlHinatCifruRoute
  '/bsc/cifru-rtl/house-cifru': typeof BscLayoutCifruRtlHouseCifruRoute
  '/bsc/cifru-rtl/opf-cifru': typeof BscLayoutCifruRtlOpfCifruRoute
  '/bsc/cifru-rtl/prdsts-vrty': typeof BscLayoutCifruRtlPrdstsVrtyRoute
  '/bsc/cltvar-yield/adlfrt': typeof BscLayoutCltvarYieldAdlfrtRoute
  '/bsc/cltvar-yield/adlfrt-imtfrt': typeof BscLayoutCltvarYieldAdlfrtImtfrtRoute
  '/bsc/cltvar-yield/cnvgt': typeof BscLayoutCltvarYieldCnvgtRoute
  '/bsc/cltvar-yield/frtvgt': typeof BscLayoutCltvarYieldFrtvgtRoute
  '/bsc/cltvar-yield/indcrp': typeof BscLayoutCltvarYieldIndcrpRoute
  '/bsc/cltvar-yield/lfyvgt': typeof BscLayoutCltvarYieldLfyvgtRoute
  '/bsc/cltvar-yield/miscgrn': typeof BscLayoutCltvarYieldMiscgrnRoute
  '/bsc/cltvar-yield/mldgrn': typeof BscLayoutCltvarYieldMldgrnRoute
  '/bsc/cltvar-yield/pls': typeof BscLayoutCltvarYieldPlsRoute
  '/bsc/cltvar-yield/rtcrp': typeof BscLayoutCltvarYieldRtcrpRoute
  '/bsc/cltvar-yield/rtvgt': typeof BscLayoutCltvarYieldRtvgtRoute
  '/bsc/cltvar-yield/whtbrl-mldgrn': typeof BscLayoutCltvarYieldWhtbrlMldgrnRoute
  '/bsc/cltvar-yield/whtbrl-rghgrn': typeof BscLayoutCltvarYieldWhtbrlRghgrnRoute
  '/bsc/ecnm/ast': typeof BscLayoutEcnmAstRoute
  '/bsc/ecnm/crast': typeof BscLayoutEcnmCrastRoute
  '/bsc/ecnm/earn': typeof BscLayoutEcnmEarnRoute
  '/bsc/ecnm/grsincm': typeof BscLayoutEcnmGrsincmRoute
  '/bsc/ecnm/key-idct': typeof BscLayoutEcnmKeyIdctRoute
  '/bsc/ecnm/lblt': typeof BscLayoutEcnmLbltRoute
  '/bsc/ecnm/lbrinp': typeof BscLayoutEcnmLbrinpRoute
  '/bsc/ecnm/mngmt-cost': typeof BscLayoutEcnmMngmtCostRoute
  '/bsc/ecnm/prdtv-idct': typeof BscLayoutEcnmPrdtvIdctRoute
  '/bsc/frmhs/age-ppltn': typeof BscLayoutFrmhsAgePpltnRoute
  '/bsc/frmhs/age-rtfrm': typeof BscLayoutFrmhsAgeRtfrmRoute
  '/bsc/frmhs/age-rtrrl': typeof BscLayoutFrmhsAgeRtrrlRoute
  '/bsc/frmhs/frmlnd-scl': typeof BscLayoutFrmhsFrmlndSclRoute
  '/bsc/frmhs/ppltn': typeof BscLayoutFrmhsPpltnRoute
  '/bsc/frmlnd/area': typeof BscLayoutFrmlndAreaRoute
  '/bsc/frmlnd/utztn': typeof BscLayoutFrmlndUtztnRoute
  '/bsc/prdctn-mtrl/agrchm-frtlzr-ntsl': typeof BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute
  '/bsc/prdctn-mtrl/frmcn-hld': typeof BscLayoutPrdctnMtrlFrmcnHldRoute
  '/spc/agrclt-env/agrclt-dstdmg': typeof SpcLayoutAgrcltEnvAgrcltDstdmgRoute
  '/spc/agrclt-env/dstdmg-type-stats': typeof SpcLayoutAgrcltEnvDstdmgTypeStatsRoute
  '/spc/agrclt-env/gwt-anls-dsbrd': typeof SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute
  '/spc/agrclt-env/gwt-wtrqlty-chag': typeof SpcLayoutAgrcltEnvGwtWtrqltyChagRoute
  '/spc/agrclt-env/item-dam-cs': typeof SpcLayoutAgrcltEnvItemDamCsRoute
  '/spc/agrclt-env/wethr': typeof SpcLayoutAgrcltEnvWethrRoute
  '/spc/agrclt-env/yrly-agrclt-dstdmg': typeof SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute
  '/spc/obsrvn/cifru-trage-dist': typeof SpcLayoutObsrvnCifruTrageDistRoute
  '/spc/obsrvn/flnt': typeof SpcLayoutObsrvnFlntRoute
  '/spc/obsrvn/obsrvn-info-cmp': typeof SpcLayoutObsrvnObsrvnInfoCmpRoute
  '/spc/obsrvn/qlty': typeof SpcLayoutObsrvnQltyRoute
  '/spc/prod/aging': typeof SpcLayoutProdAgingRoute
  '/spc/prod/cltvar-chag': typeof SpcLayoutProdCltvarChagRoute
  '/spc/prod/crop-cltvtn-map': typeof SpcLayoutProdCropCltvtnMapRoute
  '/spc/prod/rgn-cifru-cltvtn': typeof SpcLayoutProdRgnCifruCltvtnRoute
  '/spc/prod/rgn-cltvtn-harv': typeof SpcLayoutProdRgnCltvtnHarvRoute
  '/spc/rtl/crop-trade': typeof SpcLayoutRtlCropTradeRoute
  '/spc/rtl/exp': typeof SpcLayoutRtlExpRoute
  '/spc/rtl/garak-prc': typeof SpcLayoutRtlGarakPrcRoute
  '/spc/rtl/prc-dsbrd': typeof SpcLayoutRtlPrcDsbrdRoute
  '/spc/rtl/prc-predc': typeof SpcLayoutRtlPrcPredcRoute
  '/spc/rtl/whlsl-mrkt-share': typeof SpcLayoutRtlWhlslMrktShareRoute
  '/jeju-agri/detail/$id': typeof JejuAgriDetailIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/gis': typeof GisRoute
  '/login': typeof LoginRoute
  '/bsc': typeof BscRouteWithChildren
  '/bsc/_layout': typeof BscLayoutRouteWithChildren
  '/spc': typeof SpcRouteWithChildren
  '/spc/_layout': typeof SpcLayoutRouteWithChildren
  '/jeju-agri/': typeof JejuAgriIndexRoute
  '/bsc/_layout/cifru-rtl/bsc-stats': typeof BscLayoutCifruRtlBscStatsRoute
  '/bsc/_layout/cifru-rtl/cifruhyb': typeof BscLayoutCifruRtlCifruhybRoute
  '/bsc/_layout/cifru-rtl/hinat-cifru': typeof BscLayoutCifruRtlHinatCifruRoute
  '/bsc/_layout/cifru-rtl/house-cifru': typeof BscLayoutCifruRtlHouseCifruRoute
  '/bsc/_layout/cifru-rtl/opf-cifru': typeof BscLayoutCifruRtlOpfCifruRoute
  '/bsc/_layout/cifru-rtl/prdsts-vrty': typeof BscLayoutCifruRtlPrdstsVrtyRoute
  '/bsc/_layout/cltvar-yield/adlfrt': typeof BscLayoutCltvarYieldAdlfrtRoute
  '/bsc/_layout/cltvar-yield/adlfrt-imtfrt': typeof BscLayoutCltvarYieldAdlfrtImtfrtRoute
  '/bsc/_layout/cltvar-yield/cnvgt': typeof BscLayoutCltvarYieldCnvgtRoute
  '/bsc/_layout/cltvar-yield/frtvgt': typeof BscLayoutCltvarYieldFrtvgtRoute
  '/bsc/_layout/cltvar-yield/indcrp': typeof BscLayoutCltvarYieldIndcrpRoute
  '/bsc/_layout/cltvar-yield/lfyvgt': typeof BscLayoutCltvarYieldLfyvgtRoute
  '/bsc/_layout/cltvar-yield/miscgrn': typeof BscLayoutCltvarYieldMiscgrnRoute
  '/bsc/_layout/cltvar-yield/mldgrn': typeof BscLayoutCltvarYieldMldgrnRoute
  '/bsc/_layout/cltvar-yield/pls': typeof BscLayoutCltvarYieldPlsRoute
  '/bsc/_layout/cltvar-yield/rtcrp': typeof BscLayoutCltvarYieldRtcrpRoute
  '/bsc/_layout/cltvar-yield/rtvgt': typeof BscLayoutCltvarYieldRtvgtRoute
  '/bsc/_layout/cltvar-yield/whtbrl-mldgrn': typeof BscLayoutCltvarYieldWhtbrlMldgrnRoute
  '/bsc/_layout/cltvar-yield/whtbrl-rghgrn': typeof BscLayoutCltvarYieldWhtbrlRghgrnRoute
  '/bsc/_layout/ecnm/ast': typeof BscLayoutEcnmAstRoute
  '/bsc/_layout/ecnm/crast': typeof BscLayoutEcnmCrastRoute
  '/bsc/_layout/ecnm/earn': typeof BscLayoutEcnmEarnRoute
  '/bsc/_layout/ecnm/grsincm': typeof BscLayoutEcnmGrsincmRoute
  '/bsc/_layout/ecnm/key-idct': typeof BscLayoutEcnmKeyIdctRoute
  '/bsc/_layout/ecnm/lblt': typeof BscLayoutEcnmLbltRoute
  '/bsc/_layout/ecnm/lbrinp': typeof BscLayoutEcnmLbrinpRoute
  '/bsc/_layout/ecnm/mngmt-cost': typeof BscLayoutEcnmMngmtCostRoute
  '/bsc/_layout/ecnm/prdtv-idct': typeof BscLayoutEcnmPrdtvIdctRoute
  '/bsc/_layout/frmhs/age-ppltn': typeof BscLayoutFrmhsAgePpltnRoute
  '/bsc/_layout/frmhs/age-rtfrm': typeof BscLayoutFrmhsAgeRtfrmRoute
  '/bsc/_layout/frmhs/age-rtrrl': typeof BscLayoutFrmhsAgeRtrrlRoute
  '/bsc/_layout/frmhs/frmlnd-scl': typeof BscLayoutFrmhsFrmlndSclRoute
  '/bsc/_layout/frmhs/ppltn': typeof BscLayoutFrmhsPpltnRoute
  '/bsc/_layout/frmlnd/area': typeof BscLayoutFrmlndAreaRoute
  '/bsc/_layout/frmlnd/utztn': typeof BscLayoutFrmlndUtztnRoute
  '/bsc/_layout/prdctn-mtrl/agrchm-frtlzr-ntsl': typeof BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute
  '/bsc/_layout/prdctn-mtrl/frmcn-hld': typeof BscLayoutPrdctnMtrlFrmcnHldRoute
  '/spc/_layout/agrclt-env/agrclt-dstdmg': typeof SpcLayoutAgrcltEnvAgrcltDstdmgRoute
  '/spc/_layout/agrclt-env/dstdmg-type-stats': typeof SpcLayoutAgrcltEnvDstdmgTypeStatsRoute
  '/spc/_layout/agrclt-env/gwt-anls-dsbrd': typeof SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute
  '/spc/_layout/agrclt-env/gwt-wtrqlty-chag': typeof SpcLayoutAgrcltEnvGwtWtrqltyChagRoute
  '/spc/_layout/agrclt-env/item-dam-cs': typeof SpcLayoutAgrcltEnvItemDamCsRoute
  '/spc/_layout/agrclt-env/wethr': typeof SpcLayoutAgrcltEnvWethrRoute
  '/spc/_layout/agrclt-env/yrly-agrclt-dstdmg': typeof SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute
  '/spc/_layout/obsrvn/cifru-trage-dist': typeof SpcLayoutObsrvnCifruTrageDistRoute
  '/spc/_layout/obsrvn/flnt': typeof SpcLayoutObsrvnFlntRoute
  '/spc/_layout/obsrvn/obsrvn-info-cmp': typeof SpcLayoutObsrvnObsrvnInfoCmpRoute
  '/spc/_layout/obsrvn/qlty': typeof SpcLayoutObsrvnQltyRoute
  '/spc/_layout/prod/aging': typeof SpcLayoutProdAgingRoute
  '/spc/_layout/prod/cltvar-chag': typeof SpcLayoutProdCltvarChagRoute
  '/spc/_layout/prod/crop-cltvtn-map': typeof SpcLayoutProdCropCltvtnMapRoute
  '/spc/_layout/prod/rgn-cifru-cltvtn': typeof SpcLayoutProdRgnCifruCltvtnRoute
  '/spc/_layout/prod/rgn-cltvtn-harv': typeof SpcLayoutProdRgnCltvtnHarvRoute
  '/spc/_layout/rtl/crop-trade': typeof SpcLayoutRtlCropTradeRoute
  '/spc/_layout/rtl/exp': typeof SpcLayoutRtlExpRoute
  '/spc/_layout/rtl/garak-prc': typeof SpcLayoutRtlGarakPrcRoute
  '/spc/_layout/rtl/prc-dsbrd': typeof SpcLayoutRtlPrcDsbrdRoute
  '/spc/_layout/rtl/prc-predc': typeof SpcLayoutRtlPrcPredcRoute
  '/spc/_layout/rtl/whlsl-mrkt-share': typeof SpcLayoutRtlWhlslMrktShareRoute
  '/jeju-agri/detail/$id/': typeof JejuAgriDetailIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/gis'
    | '/login'
    | '/bsc'
    | '/spc'
    | '/jeju-agri'
    | '/bsc/cifru-rtl/bsc-stats'
    | '/bsc/cifru-rtl/cifruhyb'
    | '/bsc/cifru-rtl/hinat-cifru'
    | '/bsc/cifru-rtl/house-cifru'
    | '/bsc/cifru-rtl/opf-cifru'
    | '/bsc/cifru-rtl/prdsts-vrty'
    | '/bsc/cltvar-yield/adlfrt'
    | '/bsc/cltvar-yield/adlfrt-imtfrt'
    | '/bsc/cltvar-yield/cnvgt'
    | '/bsc/cltvar-yield/frtvgt'
    | '/bsc/cltvar-yield/indcrp'
    | '/bsc/cltvar-yield/lfyvgt'
    | '/bsc/cltvar-yield/miscgrn'
    | '/bsc/cltvar-yield/mldgrn'
    | '/bsc/cltvar-yield/pls'
    | '/bsc/cltvar-yield/rtcrp'
    | '/bsc/cltvar-yield/rtvgt'
    | '/bsc/cltvar-yield/whtbrl-mldgrn'
    | '/bsc/cltvar-yield/whtbrl-rghgrn'
    | '/bsc/ecnm/ast'
    | '/bsc/ecnm/crast'
    | '/bsc/ecnm/earn'
    | '/bsc/ecnm/grsincm'
    | '/bsc/ecnm/key-idct'
    | '/bsc/ecnm/lblt'
    | '/bsc/ecnm/lbrinp'
    | '/bsc/ecnm/mngmt-cost'
    | '/bsc/ecnm/prdtv-idct'
    | '/bsc/frmhs/age-ppltn'
    | '/bsc/frmhs/age-rtfrm'
    | '/bsc/frmhs/age-rtrrl'
    | '/bsc/frmhs/frmlnd-scl'
    | '/bsc/frmhs/ppltn'
    | '/bsc/frmlnd/area'
    | '/bsc/frmlnd/utztn'
    | '/bsc/prdctn-mtrl/agrchm-frtlzr-ntsl'
    | '/bsc/prdctn-mtrl/frmcn-hld'
    | '/spc/agrclt-env/agrclt-dstdmg'
    | '/spc/agrclt-env/dstdmg-type-stats'
    | '/spc/agrclt-env/gwt-anls-dsbrd'
    | '/spc/agrclt-env/gwt-wtrqlty-chag'
    | '/spc/agrclt-env/item-dam-cs'
    | '/spc/agrclt-env/wethr'
    | '/spc/agrclt-env/yrly-agrclt-dstdmg'
    | '/spc/obsrvn/cifru-trage-dist'
    | '/spc/obsrvn/flnt'
    | '/spc/obsrvn/obsrvn-info-cmp'
    | '/spc/obsrvn/qlty'
    | '/spc/prod/aging'
    | '/spc/prod/cltvar-chag'
    | '/spc/prod/crop-cltvtn-map'
    | '/spc/prod/rgn-cifru-cltvtn'
    | '/spc/prod/rgn-cltvtn-harv'
    | '/spc/rtl/crop-trade'
    | '/spc/rtl/exp'
    | '/spc/rtl/garak-prc'
    | '/spc/rtl/prc-dsbrd'
    | '/spc/rtl/prc-predc'
    | '/spc/rtl/whlsl-mrkt-share'
    | '/jeju-agri/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/gis'
    | '/login'
    | '/bsc'
    | '/spc'
    | '/jeju-agri'
    | '/bsc/cifru-rtl/bsc-stats'
    | '/bsc/cifru-rtl/cifruhyb'
    | '/bsc/cifru-rtl/hinat-cifru'
    | '/bsc/cifru-rtl/house-cifru'
    | '/bsc/cifru-rtl/opf-cifru'
    | '/bsc/cifru-rtl/prdsts-vrty'
    | '/bsc/cltvar-yield/adlfrt'
    | '/bsc/cltvar-yield/adlfrt-imtfrt'
    | '/bsc/cltvar-yield/cnvgt'
    | '/bsc/cltvar-yield/frtvgt'
    | '/bsc/cltvar-yield/indcrp'
    | '/bsc/cltvar-yield/lfyvgt'
    | '/bsc/cltvar-yield/miscgrn'
    | '/bsc/cltvar-yield/mldgrn'
    | '/bsc/cltvar-yield/pls'
    | '/bsc/cltvar-yield/rtcrp'
    | '/bsc/cltvar-yield/rtvgt'
    | '/bsc/cltvar-yield/whtbrl-mldgrn'
    | '/bsc/cltvar-yield/whtbrl-rghgrn'
    | '/bsc/ecnm/ast'
    | '/bsc/ecnm/crast'
    | '/bsc/ecnm/earn'
    | '/bsc/ecnm/grsincm'
    | '/bsc/ecnm/key-idct'
    | '/bsc/ecnm/lblt'
    | '/bsc/ecnm/lbrinp'
    | '/bsc/ecnm/mngmt-cost'
    | '/bsc/ecnm/prdtv-idct'
    | '/bsc/frmhs/age-ppltn'
    | '/bsc/frmhs/age-rtfrm'
    | '/bsc/frmhs/age-rtrrl'
    | '/bsc/frmhs/frmlnd-scl'
    | '/bsc/frmhs/ppltn'
    | '/bsc/frmlnd/area'
    | '/bsc/frmlnd/utztn'
    | '/bsc/prdctn-mtrl/agrchm-frtlzr-ntsl'
    | '/bsc/prdctn-mtrl/frmcn-hld'
    | '/spc/agrclt-env/agrclt-dstdmg'
    | '/spc/agrclt-env/dstdmg-type-stats'
    | '/spc/agrclt-env/gwt-anls-dsbrd'
    | '/spc/agrclt-env/gwt-wtrqlty-chag'
    | '/spc/agrclt-env/item-dam-cs'
    | '/spc/agrclt-env/wethr'
    | '/spc/agrclt-env/yrly-agrclt-dstdmg'
    | '/spc/obsrvn/cifru-trage-dist'
    | '/spc/obsrvn/flnt'
    | '/spc/obsrvn/obsrvn-info-cmp'
    | '/spc/obsrvn/qlty'
    | '/spc/prod/aging'
    | '/spc/prod/cltvar-chag'
    | '/spc/prod/crop-cltvtn-map'
    | '/spc/prod/rgn-cifru-cltvtn'
    | '/spc/prod/rgn-cltvtn-harv'
    | '/spc/rtl/crop-trade'
    | '/spc/rtl/exp'
    | '/spc/rtl/garak-prc'
    | '/spc/rtl/prc-dsbrd'
    | '/spc/rtl/prc-predc'
    | '/spc/rtl/whlsl-mrkt-share'
    | '/jeju-agri/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/gis'
    | '/login'
    | '/bsc'
    | '/bsc/_layout'
    | '/spc'
    | '/spc/_layout'
    | '/jeju-agri/'
    | '/bsc/_layout/cifru-rtl/bsc-stats'
    | '/bsc/_layout/cifru-rtl/cifruhyb'
    | '/bsc/_layout/cifru-rtl/hinat-cifru'
    | '/bsc/_layout/cifru-rtl/house-cifru'
    | '/bsc/_layout/cifru-rtl/opf-cifru'
    | '/bsc/_layout/cifru-rtl/prdsts-vrty'
    | '/bsc/_layout/cltvar-yield/adlfrt'
    | '/bsc/_layout/cltvar-yield/adlfrt-imtfrt'
    | '/bsc/_layout/cltvar-yield/cnvgt'
    | '/bsc/_layout/cltvar-yield/frtvgt'
    | '/bsc/_layout/cltvar-yield/indcrp'
    | '/bsc/_layout/cltvar-yield/lfyvgt'
    | '/bsc/_layout/cltvar-yield/miscgrn'
    | '/bsc/_layout/cltvar-yield/mldgrn'
    | '/bsc/_layout/cltvar-yield/pls'
    | '/bsc/_layout/cltvar-yield/rtcrp'
    | '/bsc/_layout/cltvar-yield/rtvgt'
    | '/bsc/_layout/cltvar-yield/whtbrl-mldgrn'
    | '/bsc/_layout/cltvar-yield/whtbrl-rghgrn'
    | '/bsc/_layout/ecnm/ast'
    | '/bsc/_layout/ecnm/crast'
    | '/bsc/_layout/ecnm/earn'
    | '/bsc/_layout/ecnm/grsincm'
    | '/bsc/_layout/ecnm/key-idct'
    | '/bsc/_layout/ecnm/lblt'
    | '/bsc/_layout/ecnm/lbrinp'
    | '/bsc/_layout/ecnm/mngmt-cost'
    | '/bsc/_layout/ecnm/prdtv-idct'
    | '/bsc/_layout/frmhs/age-ppltn'
    | '/bsc/_layout/frmhs/age-rtfrm'
    | '/bsc/_layout/frmhs/age-rtrrl'
    | '/bsc/_layout/frmhs/frmlnd-scl'
    | '/bsc/_layout/frmhs/ppltn'
    | '/bsc/_layout/frmlnd/area'
    | '/bsc/_layout/frmlnd/utztn'
    | '/bsc/_layout/prdctn-mtrl/agrchm-frtlzr-ntsl'
    | '/bsc/_layout/prdctn-mtrl/frmcn-hld'
    | '/spc/_layout/agrclt-env/agrclt-dstdmg'
    | '/spc/_layout/agrclt-env/dstdmg-type-stats'
    | '/spc/_layout/agrclt-env/gwt-anls-dsbrd'
    | '/spc/_layout/agrclt-env/gwt-wtrqlty-chag'
    | '/spc/_layout/agrclt-env/item-dam-cs'
    | '/spc/_layout/agrclt-env/wethr'
    | '/spc/_layout/agrclt-env/yrly-agrclt-dstdmg'
    | '/spc/_layout/obsrvn/cifru-trage-dist'
    | '/spc/_layout/obsrvn/flnt'
    | '/spc/_layout/obsrvn/obsrvn-info-cmp'
    | '/spc/_layout/obsrvn/qlty'
    | '/spc/_layout/prod/aging'
    | '/spc/_layout/prod/cltvar-chag'
    | '/spc/_layout/prod/crop-cltvtn-map'
    | '/spc/_layout/prod/rgn-cifru-cltvtn'
    | '/spc/_layout/prod/rgn-cltvtn-harv'
    | '/spc/_layout/rtl/crop-trade'
    | '/spc/_layout/rtl/exp'
    | '/spc/_layout/rtl/garak-prc'
    | '/spc/_layout/rtl/prc-dsbrd'
    | '/spc/_layout/rtl/prc-predc'
    | '/spc/_layout/rtl/whlsl-mrkt-share'
    | '/jeju-agri/detail/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  GisRoute: typeof GisRoute
  LoginRoute: typeof LoginRoute
  BscRoute: typeof BscRouteWithChildren
  SpcRoute: typeof SpcRouteWithChildren
  JejuAgriIndexRoute: typeof JejuAgriIndexRoute
  JejuAgriDetailIdIndexRoute: typeof JejuAgriDetailIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spc': {
      id: '/spc'
      path: '/spc'
      fullPath: '/spc'
      preLoaderRoute: typeof SpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bsc': {
      id: '/bsc'
      path: '/bsc'
      fullPath: '/bsc'
      preLoaderRoute: typeof BscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeju-agri/': {
      id: '/jeju-agri/'
      path: '/jeju-agri'
      fullPath: '/jeju-agri'
      preLoaderRoute: typeof JejuAgriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spc/_layout': {
      id: '/spc/_layout'
      path: '/spc'
      fullPath: '/spc'
      preLoaderRoute: typeof SpcLayoutRouteImport
      parentRoute: typeof SpcRoute
    }
    '/bsc/_layout': {
      id: '/bsc/_layout'
      path: '/bsc'
      fullPath: '/bsc'
      preLoaderRoute: typeof BscLayoutRouteImport
      parentRoute: typeof BscRoute
    }
    '/jeju-agri/detail/$id/': {
      id: '/jeju-agri/detail/$id/'
      path: '/jeju-agri/detail/$id'
      fullPath: '/jeju-agri/detail/$id'
      preLoaderRoute: typeof JejuAgriDetailIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spc/_layout/rtl/whlsl-mrkt-share': {
      id: '/spc/_layout/rtl/whlsl-mrkt-share'
      path: '/rtl/whlsl-mrkt-share'
      fullPath: '/spc/rtl/whlsl-mrkt-share'
      preLoaderRoute: typeof SpcLayoutRtlWhlslMrktShareRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/rtl/prc-predc': {
      id: '/spc/_layout/rtl/prc-predc'
      path: '/rtl/prc-predc'
      fullPath: '/spc/rtl/prc-predc'
      preLoaderRoute: typeof SpcLayoutRtlPrcPredcRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/rtl/prc-dsbrd': {
      id: '/spc/_layout/rtl/prc-dsbrd'
      path: '/rtl/prc-dsbrd'
      fullPath: '/spc/rtl/prc-dsbrd'
      preLoaderRoute: typeof SpcLayoutRtlPrcDsbrdRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/rtl/garak-prc': {
      id: '/spc/_layout/rtl/garak-prc'
      path: '/rtl/garak-prc'
      fullPath: '/spc/rtl/garak-prc'
      preLoaderRoute: typeof SpcLayoutRtlGarakPrcRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/rtl/exp': {
      id: '/spc/_layout/rtl/exp'
      path: '/rtl/exp'
      fullPath: '/spc/rtl/exp'
      preLoaderRoute: typeof SpcLayoutRtlExpRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/rtl/crop-trade': {
      id: '/spc/_layout/rtl/crop-trade'
      path: '/rtl/crop-trade'
      fullPath: '/spc/rtl/crop-trade'
      preLoaderRoute: typeof SpcLayoutRtlCropTradeRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/prod/rgn-cltvtn-harv': {
      id: '/spc/_layout/prod/rgn-cltvtn-harv'
      path: '/prod/rgn-cltvtn-harv'
      fullPath: '/spc/prod/rgn-cltvtn-harv'
      preLoaderRoute: typeof SpcLayoutProdRgnCltvtnHarvRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/prod/rgn-cifru-cltvtn': {
      id: '/spc/_layout/prod/rgn-cifru-cltvtn'
      path: '/prod/rgn-cifru-cltvtn'
      fullPath: '/spc/prod/rgn-cifru-cltvtn'
      preLoaderRoute: typeof SpcLayoutProdRgnCifruCltvtnRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/prod/crop-cltvtn-map': {
      id: '/spc/_layout/prod/crop-cltvtn-map'
      path: '/prod/crop-cltvtn-map'
      fullPath: '/spc/prod/crop-cltvtn-map'
      preLoaderRoute: typeof SpcLayoutProdCropCltvtnMapRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/prod/cltvar-chag': {
      id: '/spc/_layout/prod/cltvar-chag'
      path: '/prod/cltvar-chag'
      fullPath: '/spc/prod/cltvar-chag'
      preLoaderRoute: typeof SpcLayoutProdCltvarChagRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/prod/aging': {
      id: '/spc/_layout/prod/aging'
      path: '/prod/aging'
      fullPath: '/spc/prod/aging'
      preLoaderRoute: typeof SpcLayoutProdAgingRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/obsrvn/qlty': {
      id: '/spc/_layout/obsrvn/qlty'
      path: '/obsrvn/qlty'
      fullPath: '/spc/obsrvn/qlty'
      preLoaderRoute: typeof SpcLayoutObsrvnQltyRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/obsrvn/obsrvn-info-cmp': {
      id: '/spc/_layout/obsrvn/obsrvn-info-cmp'
      path: '/obsrvn/obsrvn-info-cmp'
      fullPath: '/spc/obsrvn/obsrvn-info-cmp'
      preLoaderRoute: typeof SpcLayoutObsrvnObsrvnInfoCmpRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/obsrvn/flnt': {
      id: '/spc/_layout/obsrvn/flnt'
      path: '/obsrvn/flnt'
      fullPath: '/spc/obsrvn/flnt'
      preLoaderRoute: typeof SpcLayoutObsrvnFlntRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/obsrvn/cifru-trage-dist': {
      id: '/spc/_layout/obsrvn/cifru-trage-dist'
      path: '/obsrvn/cifru-trage-dist'
      fullPath: '/spc/obsrvn/cifru-trage-dist'
      preLoaderRoute: typeof SpcLayoutObsrvnCifruTrageDistRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/yrly-agrclt-dstdmg': {
      id: '/spc/_layout/agrclt-env/yrly-agrclt-dstdmg'
      path: '/agrclt-env/yrly-agrclt-dstdmg'
      fullPath: '/spc/agrclt-env/yrly-agrclt-dstdmg'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/wethr': {
      id: '/spc/_layout/agrclt-env/wethr'
      path: '/agrclt-env/wethr'
      fullPath: '/spc/agrclt-env/wethr'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvWethrRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/item-dam-cs': {
      id: '/spc/_layout/agrclt-env/item-dam-cs'
      path: '/agrclt-env/item-dam-cs'
      fullPath: '/spc/agrclt-env/item-dam-cs'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvItemDamCsRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/gwt-wtrqlty-chag': {
      id: '/spc/_layout/agrclt-env/gwt-wtrqlty-chag'
      path: '/agrclt-env/gwt-wtrqlty-chag'
      fullPath: '/spc/agrclt-env/gwt-wtrqlty-chag'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvGwtWtrqltyChagRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/gwt-anls-dsbrd': {
      id: '/spc/_layout/agrclt-env/gwt-anls-dsbrd'
      path: '/agrclt-env/gwt-anls-dsbrd'
      fullPath: '/spc/agrclt-env/gwt-anls-dsbrd'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvGwtAnlsDsbrdRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/dstdmg-type-stats': {
      id: '/spc/_layout/agrclt-env/dstdmg-type-stats'
      path: '/agrclt-env/dstdmg-type-stats'
      fullPath: '/spc/agrclt-env/dstdmg-type-stats'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvDstdmgTypeStatsRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/spc/_layout/agrclt-env/agrclt-dstdmg': {
      id: '/spc/_layout/agrclt-env/agrclt-dstdmg'
      path: '/agrclt-env/agrclt-dstdmg'
      fullPath: '/spc/agrclt-env/agrclt-dstdmg'
      preLoaderRoute: typeof SpcLayoutAgrcltEnvAgrcltDstdmgRouteImport
      parentRoute: typeof SpcLayoutRoute
    }
    '/bsc/_layout/prdctn-mtrl/frmcn-hld': {
      id: '/bsc/_layout/prdctn-mtrl/frmcn-hld'
      path: '/prdctn-mtrl/frmcn-hld'
      fullPath: '/bsc/prdctn-mtrl/frmcn-hld'
      preLoaderRoute: typeof BscLayoutPrdctnMtrlFrmcnHldRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/prdctn-mtrl/agrchm-frtlzr-ntsl': {
      id: '/bsc/_layout/prdctn-mtrl/agrchm-frtlzr-ntsl'
      path: '/prdctn-mtrl/agrchm-frtlzr-ntsl'
      fullPath: '/bsc/prdctn-mtrl/agrchm-frtlzr-ntsl'
      preLoaderRoute: typeof BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmlnd/utztn': {
      id: '/bsc/_layout/frmlnd/utztn'
      path: '/frmlnd/utztn'
      fullPath: '/bsc/frmlnd/utztn'
      preLoaderRoute: typeof BscLayoutFrmlndUtztnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmlnd/area': {
      id: '/bsc/_layout/frmlnd/area'
      path: '/frmlnd/area'
      fullPath: '/bsc/frmlnd/area'
      preLoaderRoute: typeof BscLayoutFrmlndAreaRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmhs/ppltn': {
      id: '/bsc/_layout/frmhs/ppltn'
      path: '/frmhs/ppltn'
      fullPath: '/bsc/frmhs/ppltn'
      preLoaderRoute: typeof BscLayoutFrmhsPpltnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmhs/frmlnd-scl': {
      id: '/bsc/_layout/frmhs/frmlnd-scl'
      path: '/frmhs/frmlnd-scl'
      fullPath: '/bsc/frmhs/frmlnd-scl'
      preLoaderRoute: typeof BscLayoutFrmhsFrmlndSclRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmhs/age-rtrrl': {
      id: '/bsc/_layout/frmhs/age-rtrrl'
      path: '/frmhs/age-rtrrl'
      fullPath: '/bsc/frmhs/age-rtrrl'
      preLoaderRoute: typeof BscLayoutFrmhsAgeRtrrlRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmhs/age-rtfrm': {
      id: '/bsc/_layout/frmhs/age-rtfrm'
      path: '/frmhs/age-rtfrm'
      fullPath: '/bsc/frmhs/age-rtfrm'
      preLoaderRoute: typeof BscLayoutFrmhsAgeRtfrmRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/frmhs/age-ppltn': {
      id: '/bsc/_layout/frmhs/age-ppltn'
      path: '/frmhs/age-ppltn'
      fullPath: '/bsc/frmhs/age-ppltn'
      preLoaderRoute: typeof BscLayoutFrmhsAgePpltnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/prdtv-idct': {
      id: '/bsc/_layout/ecnm/prdtv-idct'
      path: '/ecnm/prdtv-idct'
      fullPath: '/bsc/ecnm/prdtv-idct'
      preLoaderRoute: typeof BscLayoutEcnmPrdtvIdctRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/mngmt-cost': {
      id: '/bsc/_layout/ecnm/mngmt-cost'
      path: '/ecnm/mngmt-cost'
      fullPath: '/bsc/ecnm/mngmt-cost'
      preLoaderRoute: typeof BscLayoutEcnmMngmtCostRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/lbrinp': {
      id: '/bsc/_layout/ecnm/lbrinp'
      path: '/ecnm/lbrinp'
      fullPath: '/bsc/ecnm/lbrinp'
      preLoaderRoute: typeof BscLayoutEcnmLbrinpRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/lblt': {
      id: '/bsc/_layout/ecnm/lblt'
      path: '/ecnm/lblt'
      fullPath: '/bsc/ecnm/lblt'
      preLoaderRoute: typeof BscLayoutEcnmLbltRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/key-idct': {
      id: '/bsc/_layout/ecnm/key-idct'
      path: '/ecnm/key-idct'
      fullPath: '/bsc/ecnm/key-idct'
      preLoaderRoute: typeof BscLayoutEcnmKeyIdctRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/grsincm': {
      id: '/bsc/_layout/ecnm/grsincm'
      path: '/ecnm/grsincm'
      fullPath: '/bsc/ecnm/grsincm'
      preLoaderRoute: typeof BscLayoutEcnmGrsincmRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/earn': {
      id: '/bsc/_layout/ecnm/earn'
      path: '/ecnm/earn'
      fullPath: '/bsc/ecnm/earn'
      preLoaderRoute: typeof BscLayoutEcnmEarnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/crast': {
      id: '/bsc/_layout/ecnm/crast'
      path: '/ecnm/crast'
      fullPath: '/bsc/ecnm/crast'
      preLoaderRoute: typeof BscLayoutEcnmCrastRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/ecnm/ast': {
      id: '/bsc/_layout/ecnm/ast'
      path: '/ecnm/ast'
      fullPath: '/bsc/ecnm/ast'
      preLoaderRoute: typeof BscLayoutEcnmAstRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/whtbrl-rghgrn': {
      id: '/bsc/_layout/cltvar-yield/whtbrl-rghgrn'
      path: '/cltvar-yield/whtbrl-rghgrn'
      fullPath: '/bsc/cltvar-yield/whtbrl-rghgrn'
      preLoaderRoute: typeof BscLayoutCltvarYieldWhtbrlRghgrnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/whtbrl-mldgrn': {
      id: '/bsc/_layout/cltvar-yield/whtbrl-mldgrn'
      path: '/cltvar-yield/whtbrl-mldgrn'
      fullPath: '/bsc/cltvar-yield/whtbrl-mldgrn'
      preLoaderRoute: typeof BscLayoutCltvarYieldWhtbrlMldgrnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/rtvgt': {
      id: '/bsc/_layout/cltvar-yield/rtvgt'
      path: '/cltvar-yield/rtvgt'
      fullPath: '/bsc/cltvar-yield/rtvgt'
      preLoaderRoute: typeof BscLayoutCltvarYieldRtvgtRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/rtcrp': {
      id: '/bsc/_layout/cltvar-yield/rtcrp'
      path: '/cltvar-yield/rtcrp'
      fullPath: '/bsc/cltvar-yield/rtcrp'
      preLoaderRoute: typeof BscLayoutCltvarYieldRtcrpRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/pls': {
      id: '/bsc/_layout/cltvar-yield/pls'
      path: '/cltvar-yield/pls'
      fullPath: '/bsc/cltvar-yield/pls'
      preLoaderRoute: typeof BscLayoutCltvarYieldPlsRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/mldgrn': {
      id: '/bsc/_layout/cltvar-yield/mldgrn'
      path: '/cltvar-yield/mldgrn'
      fullPath: '/bsc/cltvar-yield/mldgrn'
      preLoaderRoute: typeof BscLayoutCltvarYieldMldgrnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/miscgrn': {
      id: '/bsc/_layout/cltvar-yield/miscgrn'
      path: '/cltvar-yield/miscgrn'
      fullPath: '/bsc/cltvar-yield/miscgrn'
      preLoaderRoute: typeof BscLayoutCltvarYieldMiscgrnRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/lfyvgt': {
      id: '/bsc/_layout/cltvar-yield/lfyvgt'
      path: '/cltvar-yield/lfyvgt'
      fullPath: '/bsc/cltvar-yield/lfyvgt'
      preLoaderRoute: typeof BscLayoutCltvarYieldLfyvgtRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/indcrp': {
      id: '/bsc/_layout/cltvar-yield/indcrp'
      path: '/cltvar-yield/indcrp'
      fullPath: '/bsc/cltvar-yield/indcrp'
      preLoaderRoute: typeof BscLayoutCltvarYieldIndcrpRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/frtvgt': {
      id: '/bsc/_layout/cltvar-yield/frtvgt'
      path: '/cltvar-yield/frtvgt'
      fullPath: '/bsc/cltvar-yield/frtvgt'
      preLoaderRoute: typeof BscLayoutCltvarYieldFrtvgtRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/cnvgt': {
      id: '/bsc/_layout/cltvar-yield/cnvgt'
      path: '/cltvar-yield/cnvgt'
      fullPath: '/bsc/cltvar-yield/cnvgt'
      preLoaderRoute: typeof BscLayoutCltvarYieldCnvgtRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/adlfrt-imtfrt': {
      id: '/bsc/_layout/cltvar-yield/adlfrt-imtfrt'
      path: '/cltvar-yield/adlfrt-imtfrt'
      fullPath: '/bsc/cltvar-yield/adlfrt-imtfrt'
      preLoaderRoute: typeof BscLayoutCltvarYieldAdlfrtImtfrtRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cltvar-yield/adlfrt': {
      id: '/bsc/_layout/cltvar-yield/adlfrt'
      path: '/cltvar-yield/adlfrt'
      fullPath: '/bsc/cltvar-yield/adlfrt'
      preLoaderRoute: typeof BscLayoutCltvarYieldAdlfrtRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cifru-rtl/prdsts-vrty': {
      id: '/bsc/_layout/cifru-rtl/prdsts-vrty'
      path: '/cifru-rtl/prdsts-vrty'
      fullPath: '/bsc/cifru-rtl/prdsts-vrty'
      preLoaderRoute: typeof BscLayoutCifruRtlPrdstsVrtyRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cifru-rtl/opf-cifru': {
      id: '/bsc/_layout/cifru-rtl/opf-cifru'
      path: '/cifru-rtl/opf-cifru'
      fullPath: '/bsc/cifru-rtl/opf-cifru'
      preLoaderRoute: typeof BscLayoutCifruRtlOpfCifruRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cifru-rtl/house-cifru': {
      id: '/bsc/_layout/cifru-rtl/house-cifru'
      path: '/cifru-rtl/house-cifru'
      fullPath: '/bsc/cifru-rtl/house-cifru'
      preLoaderRoute: typeof BscLayoutCifruRtlHouseCifruRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cifru-rtl/hinat-cifru': {
      id: '/bsc/_layout/cifru-rtl/hinat-cifru'
      path: '/cifru-rtl/hinat-cifru'
      fullPath: '/bsc/cifru-rtl/hinat-cifru'
      preLoaderRoute: typeof BscLayoutCifruRtlHinatCifruRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cifru-rtl/cifruhyb': {
      id: '/bsc/_layout/cifru-rtl/cifruhyb'
      path: '/cifru-rtl/cifruhyb'
      fullPath: '/bsc/cifru-rtl/cifruhyb'
      preLoaderRoute: typeof BscLayoutCifruRtlCifruhybRouteImport
      parentRoute: typeof BscLayoutRoute
    }
    '/bsc/_layout/cifru-rtl/bsc-stats': {
      id: '/bsc/_layout/cifru-rtl/bsc-stats'
      path: '/cifru-rtl/bsc-stats'
      fullPath: '/bsc/cifru-rtl/bsc-stats'
      preLoaderRoute: typeof BscLayoutCifruRtlBscStatsRouteImport
      parentRoute: typeof BscLayoutRoute
    }
  }
}

interface BscLayoutRouteChildren {
  BscLayoutCifruRtlBscStatsRoute: typeof BscLayoutCifruRtlBscStatsRoute
  BscLayoutCifruRtlCifruhybRoute: typeof BscLayoutCifruRtlCifruhybRoute
  BscLayoutCifruRtlHinatCifruRoute: typeof BscLayoutCifruRtlHinatCifruRoute
  BscLayoutCifruRtlHouseCifruRoute: typeof BscLayoutCifruRtlHouseCifruRoute
  BscLayoutCifruRtlOpfCifruRoute: typeof BscLayoutCifruRtlOpfCifruRoute
  BscLayoutCifruRtlPrdstsVrtyRoute: typeof BscLayoutCifruRtlPrdstsVrtyRoute
  BscLayoutCltvarYieldAdlfrtRoute: typeof BscLayoutCltvarYieldAdlfrtRoute
  BscLayoutCltvarYieldAdlfrtImtfrtRoute: typeof BscLayoutCltvarYieldAdlfrtImtfrtRoute
  BscLayoutCltvarYieldCnvgtRoute: typeof BscLayoutCltvarYieldCnvgtRoute
  BscLayoutCltvarYieldFrtvgtRoute: typeof BscLayoutCltvarYieldFrtvgtRoute
  BscLayoutCltvarYieldIndcrpRoute: typeof BscLayoutCltvarYieldIndcrpRoute
  BscLayoutCltvarYieldLfyvgtRoute: typeof BscLayoutCltvarYieldLfyvgtRoute
  BscLayoutCltvarYieldMiscgrnRoute: typeof BscLayoutCltvarYieldMiscgrnRoute
  BscLayoutCltvarYieldMldgrnRoute: typeof BscLayoutCltvarYieldMldgrnRoute
  BscLayoutCltvarYieldPlsRoute: typeof BscLayoutCltvarYieldPlsRoute
  BscLayoutCltvarYieldRtcrpRoute: typeof BscLayoutCltvarYieldRtcrpRoute
  BscLayoutCltvarYieldRtvgtRoute: typeof BscLayoutCltvarYieldRtvgtRoute
  BscLayoutCltvarYieldWhtbrlMldgrnRoute: typeof BscLayoutCltvarYieldWhtbrlMldgrnRoute
  BscLayoutCltvarYieldWhtbrlRghgrnRoute: typeof BscLayoutCltvarYieldWhtbrlRghgrnRoute
  BscLayoutEcnmAstRoute: typeof BscLayoutEcnmAstRoute
  BscLayoutEcnmCrastRoute: typeof BscLayoutEcnmCrastRoute
  BscLayoutEcnmEarnRoute: typeof BscLayoutEcnmEarnRoute
  BscLayoutEcnmGrsincmRoute: typeof BscLayoutEcnmGrsincmRoute
  BscLayoutEcnmKeyIdctRoute: typeof BscLayoutEcnmKeyIdctRoute
  BscLayoutEcnmLbltRoute: typeof BscLayoutEcnmLbltRoute
  BscLayoutEcnmLbrinpRoute: typeof BscLayoutEcnmLbrinpRoute
  BscLayoutEcnmMngmtCostRoute: typeof BscLayoutEcnmMngmtCostRoute
  BscLayoutEcnmPrdtvIdctRoute: typeof BscLayoutEcnmPrdtvIdctRoute
  BscLayoutFrmhsAgePpltnRoute: typeof BscLayoutFrmhsAgePpltnRoute
  BscLayoutFrmhsAgeRtfrmRoute: typeof BscLayoutFrmhsAgeRtfrmRoute
  BscLayoutFrmhsAgeRtrrlRoute: typeof BscLayoutFrmhsAgeRtrrlRoute
  BscLayoutFrmhsFrmlndSclRoute: typeof BscLayoutFrmhsFrmlndSclRoute
  BscLayoutFrmhsPpltnRoute: typeof BscLayoutFrmhsPpltnRoute
  BscLayoutFrmlndAreaRoute: typeof BscLayoutFrmlndAreaRoute
  BscLayoutFrmlndUtztnRoute: typeof BscLayoutFrmlndUtztnRoute
  BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute: typeof BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute
  BscLayoutPrdctnMtrlFrmcnHldRoute: typeof BscLayoutPrdctnMtrlFrmcnHldRoute
}

const BscLayoutRouteChildren: BscLayoutRouteChildren = {
  BscLayoutCifruRtlBscStatsRoute: BscLayoutCifruRtlBscStatsRoute,
  BscLayoutCifruRtlCifruhybRoute: BscLayoutCifruRtlCifruhybRoute,
  BscLayoutCifruRtlHinatCifruRoute: BscLayoutCifruRtlHinatCifruRoute,
  BscLayoutCifruRtlHouseCifruRoute: BscLayoutCifruRtlHouseCifruRoute,
  BscLayoutCifruRtlOpfCifruRoute: BscLayoutCifruRtlOpfCifruRoute,
  BscLayoutCifruRtlPrdstsVrtyRoute: BscLayoutCifruRtlPrdstsVrtyRoute,
  BscLayoutCltvarYieldAdlfrtRoute: BscLayoutCltvarYieldAdlfrtRoute,
  BscLayoutCltvarYieldAdlfrtImtfrtRoute: BscLayoutCltvarYieldAdlfrtImtfrtRoute,
  BscLayoutCltvarYieldCnvgtRoute: BscLayoutCltvarYieldCnvgtRoute,
  BscLayoutCltvarYieldFrtvgtRoute: BscLayoutCltvarYieldFrtvgtRoute,
  BscLayoutCltvarYieldIndcrpRoute: BscLayoutCltvarYieldIndcrpRoute,
  BscLayoutCltvarYieldLfyvgtRoute: BscLayoutCltvarYieldLfyvgtRoute,
  BscLayoutCltvarYieldMiscgrnRoute: BscLayoutCltvarYieldMiscgrnRoute,
  BscLayoutCltvarYieldMldgrnRoute: BscLayoutCltvarYieldMldgrnRoute,
  BscLayoutCltvarYieldPlsRoute: BscLayoutCltvarYieldPlsRoute,
  BscLayoutCltvarYieldRtcrpRoute: BscLayoutCltvarYieldRtcrpRoute,
  BscLayoutCltvarYieldRtvgtRoute: BscLayoutCltvarYieldRtvgtRoute,
  BscLayoutCltvarYieldWhtbrlMldgrnRoute: BscLayoutCltvarYieldWhtbrlMldgrnRoute,
  BscLayoutCltvarYieldWhtbrlRghgrnRoute: BscLayoutCltvarYieldWhtbrlRghgrnRoute,
  BscLayoutEcnmAstRoute: BscLayoutEcnmAstRoute,
  BscLayoutEcnmCrastRoute: BscLayoutEcnmCrastRoute,
  BscLayoutEcnmEarnRoute: BscLayoutEcnmEarnRoute,
  BscLayoutEcnmGrsincmRoute: BscLayoutEcnmGrsincmRoute,
  BscLayoutEcnmKeyIdctRoute: BscLayoutEcnmKeyIdctRoute,
  BscLayoutEcnmLbltRoute: BscLayoutEcnmLbltRoute,
  BscLayoutEcnmLbrinpRoute: BscLayoutEcnmLbrinpRoute,
  BscLayoutEcnmMngmtCostRoute: BscLayoutEcnmMngmtCostRoute,
  BscLayoutEcnmPrdtvIdctRoute: BscLayoutEcnmPrdtvIdctRoute,
  BscLayoutFrmhsAgePpltnRoute: BscLayoutFrmhsAgePpltnRoute,
  BscLayoutFrmhsAgeRtfrmRoute: BscLayoutFrmhsAgeRtfrmRoute,
  BscLayoutFrmhsAgeRtrrlRoute: BscLayoutFrmhsAgeRtrrlRoute,
  BscLayoutFrmhsFrmlndSclRoute: BscLayoutFrmhsFrmlndSclRoute,
  BscLayoutFrmhsPpltnRoute: BscLayoutFrmhsPpltnRoute,
  BscLayoutFrmlndAreaRoute: BscLayoutFrmlndAreaRoute,
  BscLayoutFrmlndUtztnRoute: BscLayoutFrmlndUtztnRoute,
  BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute:
    BscLayoutPrdctnMtrlAgrchmFrtlzrNtslRoute,
  BscLayoutPrdctnMtrlFrmcnHldRoute: BscLayoutPrdctnMtrlFrmcnHldRoute,
}

const BscLayoutRouteWithChildren = BscLayoutRoute._addFileChildren(
  BscLayoutRouteChildren,
)

interface BscRouteChildren {
  BscLayoutRoute: typeof BscLayoutRouteWithChildren
}

const BscRouteChildren: BscRouteChildren = {
  BscLayoutRoute: BscLayoutRouteWithChildren,
}

const BscRouteWithChildren = BscRoute._addFileChildren(BscRouteChildren)

interface SpcLayoutRouteChildren {
  SpcLayoutAgrcltEnvAgrcltDstdmgRoute: typeof SpcLayoutAgrcltEnvAgrcltDstdmgRoute
  SpcLayoutAgrcltEnvDstdmgTypeStatsRoute: typeof SpcLayoutAgrcltEnvDstdmgTypeStatsRoute
  SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute: typeof SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute
  SpcLayoutAgrcltEnvGwtWtrqltyChagRoute: typeof SpcLayoutAgrcltEnvGwtWtrqltyChagRoute
  SpcLayoutAgrcltEnvItemDamCsRoute: typeof SpcLayoutAgrcltEnvItemDamCsRoute
  SpcLayoutAgrcltEnvWethrRoute: typeof SpcLayoutAgrcltEnvWethrRoute
  SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute: typeof SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute
  SpcLayoutObsrvnCifruTrageDistRoute: typeof SpcLayoutObsrvnCifruTrageDistRoute
  SpcLayoutObsrvnFlntRoute: typeof SpcLayoutObsrvnFlntRoute
  SpcLayoutObsrvnObsrvnInfoCmpRoute: typeof SpcLayoutObsrvnObsrvnInfoCmpRoute
  SpcLayoutObsrvnQltyRoute: typeof SpcLayoutObsrvnQltyRoute
  SpcLayoutProdAgingRoute: typeof SpcLayoutProdAgingRoute
  SpcLayoutProdCltvarChagRoute: typeof SpcLayoutProdCltvarChagRoute
  SpcLayoutProdCropCltvtnMapRoute: typeof SpcLayoutProdCropCltvtnMapRoute
  SpcLayoutProdRgnCifruCltvtnRoute: typeof SpcLayoutProdRgnCifruCltvtnRoute
  SpcLayoutProdRgnCltvtnHarvRoute: typeof SpcLayoutProdRgnCltvtnHarvRoute
  SpcLayoutRtlCropTradeRoute: typeof SpcLayoutRtlCropTradeRoute
  SpcLayoutRtlExpRoute: typeof SpcLayoutRtlExpRoute
  SpcLayoutRtlGarakPrcRoute: typeof SpcLayoutRtlGarakPrcRoute
  SpcLayoutRtlPrcDsbrdRoute: typeof SpcLayoutRtlPrcDsbrdRoute
  SpcLayoutRtlPrcPredcRoute: typeof SpcLayoutRtlPrcPredcRoute
  SpcLayoutRtlWhlslMrktShareRoute: typeof SpcLayoutRtlWhlslMrktShareRoute
}

const SpcLayoutRouteChildren: SpcLayoutRouteChildren = {
  SpcLayoutAgrcltEnvAgrcltDstdmgRoute: SpcLayoutAgrcltEnvAgrcltDstdmgRoute,
  SpcLayoutAgrcltEnvDstdmgTypeStatsRoute:
    SpcLayoutAgrcltEnvDstdmgTypeStatsRoute,
  SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute: SpcLayoutAgrcltEnvGwtAnlsDsbrdRoute,
  SpcLayoutAgrcltEnvGwtWtrqltyChagRoute: SpcLayoutAgrcltEnvGwtWtrqltyChagRoute,
  SpcLayoutAgrcltEnvItemDamCsRoute: SpcLayoutAgrcltEnvItemDamCsRoute,
  SpcLayoutAgrcltEnvWethrRoute: SpcLayoutAgrcltEnvWethrRoute,
  SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute:
    SpcLayoutAgrcltEnvYrlyAgrcltDstdmgRoute,
  SpcLayoutObsrvnCifruTrageDistRoute: SpcLayoutObsrvnCifruTrageDistRoute,
  SpcLayoutObsrvnFlntRoute: SpcLayoutObsrvnFlntRoute,
  SpcLayoutObsrvnObsrvnInfoCmpRoute: SpcLayoutObsrvnObsrvnInfoCmpRoute,
  SpcLayoutObsrvnQltyRoute: SpcLayoutObsrvnQltyRoute,
  SpcLayoutProdAgingRoute: SpcLayoutProdAgingRoute,
  SpcLayoutProdCltvarChagRoute: SpcLayoutProdCltvarChagRoute,
  SpcLayoutProdCropCltvtnMapRoute: SpcLayoutProdCropCltvtnMapRoute,
  SpcLayoutProdRgnCifruCltvtnRoute: SpcLayoutProdRgnCifruCltvtnRoute,
  SpcLayoutProdRgnCltvtnHarvRoute: SpcLayoutProdRgnCltvtnHarvRoute,
  SpcLayoutRtlCropTradeRoute: SpcLayoutRtlCropTradeRoute,
  SpcLayoutRtlExpRoute: SpcLayoutRtlExpRoute,
  SpcLayoutRtlGarakPrcRoute: SpcLayoutRtlGarakPrcRoute,
  SpcLayoutRtlPrcDsbrdRoute: SpcLayoutRtlPrcDsbrdRoute,
  SpcLayoutRtlPrcPredcRoute: SpcLayoutRtlPrcPredcRoute,
  SpcLayoutRtlWhlslMrktShareRoute: SpcLayoutRtlWhlslMrktShareRoute,
}

const SpcLayoutRouteWithChildren = SpcLayoutRoute._addFileChildren(
  SpcLayoutRouteChildren,
)

interface SpcRouteChildren {
  SpcLayoutRoute: typeof SpcLayoutRouteWithChildren
}

const SpcRouteChildren: SpcRouteChildren = {
  SpcLayoutRoute: SpcLayoutRouteWithChildren,
}

const SpcRouteWithChildren = SpcRoute._addFileChildren(SpcRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  GisRoute: GisRoute,
  LoginRoute: LoginRoute,
  BscRoute: BscRouteWithChildren,
  SpcRoute: SpcRouteWithChildren,
  JejuAgriIndexRoute: JejuAgriIndexRoute,
  JejuAgriDetailIdIndexRoute: JejuAgriDetailIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
